### ISSUE TITLE
World Wonder - Click Area

### ISSUE THREAD

**Issue by ghost** [yi12345/TravianZ#102]
The click area of the world wonder should be optimized!

**Comment by akshay9** [comment]
plz elaborate

**Comment by ghost** [comment]
Ok, I try to explain, but you have to try it yourself too!

When I have my world wonder in my village I cant click on it at every spot of it to go to the building.

**Comment by gamerx159** [comment]
mhm... I know, it's not bug :)... But need know how install natars :)

**Comment by MOus** [comment]
Plz how i can instal natar and World Wonder in my serveur ? script ! ? You have script WW actif ?
