### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gamerx159** [yi12345/TravianZ#104]
Why sometimes i had error?
Warning: mysql_fetch_array() expects parameter 1 to be resource, boolean given in /home/****/public_html/GameEngine/Database/db_MYSQL.php on line 263
please help :)

**Comment by akshay9** [comment]
does it happen every time or happens when u search sum thing ??

**Comment by gamerx159** [comment]
if realy i don't know, when ~20 players play sometimes drop this error, but today i test server and drop this error and he don't disappeared in ~5 min.

srry my engish bad, but i thing u understand :)

**Comment by gamerx159** [comment]
P.S this not host problem..
http://www.cybertechhelp.com/forums/showthread.php?t=207417

**Comment by gamerx159** [comment]
- it's ally problem too :)

**Comment by gamerx159** [comment]
Close..
