### ISSUE TITLE
finish all constructions

### ISSUE THREAD

**Issue by ayour55** [yi12345/TravianZ#105]
Hi friends; 
there is a problem in the last version ; when a player clicks on "finish all constructions and researches for 2 gold" this operation actually finish but they still showing in the mais page and time  is counting
Thank you ;

**Comment by akshay9** [comment]
see this commit on my forked project
https://github.com/akshay9/TravianZ/commit/5f146c08d5aaff4ed7a867dd4176d152b7921267
or just update the fix through auto update system

**Comment by ayour55** [comment]
Ok thanks a lot :) ai apreciaite your help

**Comment by inblackhole** [comment]
Another problem.

First enable Travian Plus.
You are building a field.
Queue the same field you are building. ( put it in waiting loop)
Complete construction immediately.
**Problem:** The field is only upgraded with 1 level.
2 level should be upgraded.
