### ISSUE TITLE
Ally invite error

### ISSUE THREAD

**Issue by gamerx159** [yi12345/TravianZ#113]
hi all, i have problem with ally invite.. I had error when i wanna invite ppl.

Warning: mysql_fetch_array() expects parameter 1 to be resource, boolean given in /home/zuikyys/public_html/GameEngine/Database/db_MYSQL.php on line 263 

And maybe somebody can create system, when ppl is not active system delete him in 7 day?

Fullhdpixel issue:
Inviting doesn't work at all!

It just says: "Please insert name"

**Comment by gamerx159** [comment]
mhm i have code which ally invite work ;/

**Comment by ghost** [comment]
Can you share it please? Thanks in advance!!@

**Comment by gamerx159** [comment]
invite me skype gamerx159 :)
