### ISSUE TITLE
Just wanna Ask.. ^^

### ISSUE THREAD

**Issue by crosskyo** [yi12345/TravianZ#115]
yi12345, i have one question.. do you know how to remove scout ??
i want my scout "Equites Legati, Scout, Pathfinder" cant be reaserched in academy..
do you know how to make that happend? what script should i change to make it happend? please im really need your help

Thanks

**Comment by yi12345** [comment]
i can to check it, but i haven't time, you can ask in ragezone or something...
i think another people can help you..

**Comment by crosskyo** [comment]
But I've ask in ragezone, but no one can help me..
And I don't know the other place where I can ask something about
travian except ragezone and you..
If u have time please check it, you're the only one who can help me..
