### ISSUE TITLE
I have a bug with attacks...

### ISSUE THREAD

**Issue by Playinedit** [yi12345/TravianZ#137]
http://travian-reports.net/us/report/187589843a4

http://travian-reports.net/us/report/18759220bda

http://travian-reports.net/us/report/187592653c5

**Comment by akshay9** [comment]
actually troops die but just they are not shown

**Comment by tierrarara** [comment]
in the original travian, if you lose the attack you can't see the troops of the enemy, you must be include spy

**Comment by yi12345** [comment]
there are no bugs here, this is should be like that.
