### ISSUE TITLE
Bug with granary

### ISSUE THREAD

**Issue by ruffo** [yi12345/TravianZ#139]
When selecting granary in your village shows php code.
STORAGE_MULTIPLIER is set to 1000
http://imageshack.us/photo/my-images/207/buggranary.png/

**Comment by akshay9** [comment]
that bug happens because there is a particular restrictions on max number of digits a number can have in a cell.
so when the STORAGE_MULTIPLIER is multiplied by the building time it exceeds that limit.
so set the STORAGE_MULTIPLIER less than 200.

**Comment by ruffo** [comment]
OK! I'll do it!
Thanks!
