### ISSUE TITLE
Settler Bugs

### ISSUE THREAD

**Issue by crosskyo** [yi12345/TravianZ#140]
i realize this bug when i trying to train settler but dont have enough resource..

when u have residence lv 10 and u can Train settler.. but u dont have enough resource to train, that will show you 0 settler can be train but just try put 3 settler for example and train it!

u can train that settler although u dont have enough resource..

how to fix that? 

thanks for your effort... 
Note: sorry for my bad english

**Comment by Shadowss** [comment]
Will be fixed this bug , i test it , you are right

**Comment by Shadowss** [comment]
Fixed
