### ISSUE TITLE
Nataren non showing in statistic

### ISSUE THREAD

**Issue by ruffo** [yi12345/TravianZ#144]
The Natars Player is not showing in the statistic

**Comment by yi12345** [comment]
is not bug, and you can change it easily if you want:
Ranking.php - replace line 203 with this:
AND " . TB_PREFIX . "users.tribe <= 5 ORDER BY totalpop DESC, totalvillages DESC, userid DESC";

**Comment by ruffo** [comment]
It is possible for this option to be implemented in the configuration?

**Comment by yi12345** [comment]
i did it, download the last version and install.
