### ISSUE TITLE
How to fix this hack??

### ISSUE THREAD

**Issue by NIKO28** [yi12345/TravianZ#151]
http://www.inforge.net/community/travian-hacks-bots-e-cheats/276462-rel-travian-pserver-cheats-hack.html

How to put this fix http://www.inforge.net/community/travian/278026-fix-hack-di-err%F8r218-come-non-farselo-ownare-senza-pagare-xd-fix.html in this version?

**Comment by skysea** [comment]
I'am testing,program is working

**Comment by NIKO28** [comment]
yes, i know, all italian server are hacker with this program... @yi12345 can u make a fix for this?

**Comment by gamerx159** [comment]
mhm... NIKO28 i added this code, and now hack don't work :)

**Comment by NIKO28** [comment]
What code?

**Comment by gamerx159** [comment]
"How to put this fix http://www.inforge.net/community/travian/278026-fix-hack-di-err%F8r218-come-non-farselo-ownare-senza-pagare-xd-fix.html in this version?"
this

**Comment by NIKO28** [comment]
This work, but now u can't change ur psassword
