### ISSUE TITLE
Hi your scripts message not work

### ISSUE THREAD

**Issue by Tayyip** [yi12345/TravianZ#162]
Message dont work
you watch video 
http://www.youtube.com/watch?v=0dE6nbfGxSs&feature=youtu.be
http://tr.ayancikspor.tk

**Comment by gamerx159** [comment]
https://github.com/yi12345/TravianZ/issues/157

**Comment by gamerx159** [comment]
if works, close issue:)

**Comment by Tayyip** [comment]
ok
