### ISSUE TITLE
BUG ~ Return to Server link on admin panel ~ Fixed

### ISSUE THREAD

**Issue by sTimulated** [yi12345/TravianZ#165]
Return to server link was missing a /

Edit the admin.php on line 95

Was
<a href="<?php echo SERVER; ?>dorf1.php">Return to the server</a>

Fixed
<a href="<?php echo SERVER; ?>/dorf1.php">Return to the server</a>

I'm not a coder,just a user.
This works for me anyway.

**Comment by gamerx159** [comment]
Close Issue :)
