### ISSUE TITLE
Oasis's nature Bug

### ISSUE THREAD

**Issue by IngMak** [yi12345/TravianZ#169]
Hello, I'm a fan of Travian, this project save my life.

I notice nature troop in oasis never grow up, i think is a problem with 'lastupdate' value on bd.

Better explanation(sorry about my english)::
while I surf into code saw the function $this->oasisResoucesProduce(); in Automation.php update the value of  'lastupdate' and after  the function $this->regenerateOasisTroops(); uses the same variable.

I think  oasisResoucesProduce() always going to be a problem for regenerateOasisTroops() beacuse both uses 'lastupdate' value from DB.

**Comment by IngMak** [comment]
Well, I realized a deep search into code and detect the problem in function populateOasisUnits($wid, $high)

this code: $basearray = $this->getOasisInfo($wid); return NULL , it's here were the problem begins.
$basearray['oasistype'] is NULL, the sentence switch($basearray['oasistype']){.......} doesn't work

this method $basearray = $this->getOasisInfo($wid); have the query: $q = "SELECT \* FROM " . TB_PREFIX . "odata where wref = $wid"; 

I search into DB the table odata and noticed 'oasistype' not exist, but yes in wdata.

my temporally fix is:

delete code: $basearray = $this->getOasisInfo($wid);

add code:
$fix="SELECT \* FROM " . TB_PREFIX . "wdata WHERE id='$wid'";
                   $result = mysql_query($fix, $this->connection);
        $basearray=mysql_fetch_assoc($result);

**Comment by IngMak** [comment]
Sorry, it 3rd time  I post here. there is another problem.

delete code: 
if($basearray2['high'] == 0){
          $max = rand(15,30);
          }elseif($basearray2['high'] == 1){
          $max = rand(70,90);
          }elseif($basearray2['high'] == 2){
          $max = rand(100,140);
          }

add code: 
 if($high == 0){
          $max = rand(15,30);
          }elseif($high == 1){
          $max = rand(70,90);
          }elseif($high == 2){
          $max = rand(100,140);
          }

**Comment by IngMak** [comment]
Hi there, i hoped this hithub isn't dead.
I proposed my fix for oasis's nature.
1. In the database, table: odata, lastupdatetroops field is added to control only the generation of nature. (To create data are the same as 'lastupdate').
   The need is given because resources are generated in dependence 'lastupdate' and this function updates this variable in the DB.
2. It reimplements regenerateOasisTroops function , which is in Automation.php

The query: $ q = "SELECT \* FROM". TB_PREFIX. "odata where conqured = 0 and $ time - lastupdate> 3600";
Is changed to: $ q = "SELECT \* FROM". TB_PREFIX. "odata where conqured = 0 and $ time - lastupdatetroops> 3600";

PS: Note the use of 'lastupdatetroops'.
1. the function call: $ database-> updateOasis ($ oasis ['wref']);
   Is changed to: $ database-> updateOasisTroops ($ oasis ['wref']);

Db_MYSQL.php is added in a new feature, the following code:

 updateOasisTroops function ($ vid) {
$ Time = time ();
$ Q = "UPDATE". TB_PREFIX. "odata set lastupdatetroops = $ time where wref = $ vid";
return mysql_query ($ q, $ this-> connection);
}

PS: Note that this function is identical to updateOasis ($ vid), so now the query uses the 'lastupdatetroops' to work.

**Comment by ghost** [comment]
Is this request pulled?

**Comment by Shadowss** [comment]
Fixed
