### ISSUE TITLE
Please fix Setler bugg!! 

### ISSUE THREAD

**Issue by Foxuae** [yi12345/TravianZ#17]
DELETE 4294966344 Setler pls! BIG BUG!!!!!!!!!

**Comment by yi12345** [comment]
fixed (this appear when try to train traps, no?)

**Comment by Foxuae** [comment]
sit Not fixed the settler bug? :)

**Comment by yi12345** [comment]
when you got this bug?

**Comment by Foxuae** [comment]
i got This bug when i Try To Attack Any One 
and Sometimes i Got This Bug to Fix This Bug i Have To Log off Than Log in i can After that Attack Without Any Bug

**Comment by yi12345** [comment]
i don't know about that, i saw bug of settlers when you try to train traps, but in very old version.

**Comment by Foxuae** [comment]
see More for this Bug
http://www.youtube.com/watch?v=91Qz6lJtbBU&feature=youtu.be
