### ISSUE TITLE
Admin Panel Problem

### ISSUE THREAD

**Issue by HellIsCool** [yi12345/TravianZ#186]
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, [no address given] and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

**Comment by akshay9** [comment]
it is your server problem.
try deleting the .htaccess file

**Comment by HellIsCool** [comment]
thanks man it is working now.
