### ISSUE TITLE
wtf?

### ISSUE THREAD

**Issue by gamerx159** [yi12345/TravianZ#19]
Hey, maybe you can fix it?
http://travian-reports.net/us/report/1710130d648
http://travian-reports.net/us/report/1710114d294

**Comment by yi12345** [comment]
i don't know about it so i can't fix anything, try to download my version again and reinstall your server

**Comment by gamerx159** [comment]
http://travian-reports.net/us/report/17114717f03
how caeseris can demolish Catapult Academy?

**Comment by yi12345** [comment]
i don't know, do what i write you in the previous comment and maybe it will work
