### ISSUE TITLE
 Quest Load....

### ISSUE THREAD

**Issue by mafiadek** [yi12345/TravianZ#202]
Help Me please
quest Load....
http://prntscr.com/ycpbn

**Comment by yi12345** [comment]
are you using free host?

**Comment by mafiadek** [comment]
I did not use the free hosts.

Sorry My English.

**Comment by mafiadek** [comment]
Help me please

**Comment by yi12345** [comment]
is should be your host (even if it not free, maybe he have problem with this code, because it work for others) or you haven't the correct quest file.
try download the files again and if is don't work then reinstall. if is still don't work, try to change your host.
