### ISSUE TITLE
MYSQL error while installing

### ISSUE THREAD

**Issue by Dylan96** [yi12345/TravianZ#212]
Parse error: syntax error, unexpected T_PUBLIC in /membri/travianxt/GameEngine/Database/db_MYSQL.php on line 436

I get this error right after creating the Multihunter, i tried with MySQLi but i have this similar error:

Parse error: syntax error, unexpected T_PUBLIC in /membri/travianxt/GameEngine/Database/db_MYSQLi.php on line 439

**Comment by yidebug** [comment]
same problem
 PHP Parse error:  syntax error, unexpected T_PUBLIC in /var/www/trv1/GameEngine/Database/db_MYSQL.php on line 436, referer: http://192.168.0.61/trv1/install/index.php?s=4
I tried it in two different servers and both  mysql and  mysqli

**Comment by inblackhole** [comment]
Edit db_MYSQL.php，find and replace following function:

``` javascript
    function caststruc($user) {
        //loop search village user
        $query = mysql_query("SELECT * FROM ".TB_PREFIX."vdata WHERE owner = ".$user."");
        while($villaggi_array = mysql_fetch_array($query)){
            //loop structure village
            $query1 = mysql_query("SELECT * FROM ".TB_PREFIX."fdata WHERE vref = ".$villaggi_array['wref']."");
            $strutture= mysql_fetch_array($query1);
            return $strutture;
        }
    }
```

**Comment by Dylan96** [comment]
Ok, now it works. Thanks.
