### ISSUE TITLE
timezone

### ISSUE THREAD

**Issue by SiavashBamshadnia** [yi12345/TravianZ#233]
Hello
How can I change the TravianZ time zone?
please answer me
thanks

**Comment by hexcoded** [comment]
I think its not implemented yet.There is a hidden section in user profile where you can set timezone ,but its not active (\Templates\Profile\preference.tpl) The easiest way is to change time zone in php.ini on the web server.

**Comment by gamerx159** [comment]
I think you can change timezone in Generator.php file, in ~100 line. I remember i change in this line when i have travianx advocaite files.

**Comment by uttkarshyadav** [comment]
Hey Guys You Can Change Your Timezone After Installing The Game.
Go To=> GameEngine=>config.php
Add this Code After <?php

date_default_timezone_set('Your Time-Zone');

And You Done.

Thanks!!

Uttkarsh Yadav
