### ISSUE TITLE
In start...

### ISSUE THREAD

**Issue by xrobikx** [yi12345/TravianZ#239]
This is after uplouad files on server and put adress.

http://zpr.unas.cz

berofe 1st step: http://zpr.unas.cz/install/

Parse error: parse error, expecting `T_OLD_FUNCTION' or`T_FUNCTION' or `T_VAR' or`'}'' in /3w/unas.cz/z/zpr/install/templates/script.tpl on line 23

Fatal error: Undefined class name 'ihg_progressbar' in /3w/unas.cz/z/zpr/install/index.php on line 45

What can I do with it?

**Comment by kariha** [comment]
is hosting problem. This issue should be closed.
