### ISSUE TITLE
Gold is taken from user when it shouldn't be...

### ISSUE THREAD

**Issue by ghost** [yi12345/TravianZ#255]
hey,

I found another bug in this script.

When I want to complete all building tasks instantly by using 2 gold, I ALWAYS lose 2 gold when I click the left-hand button ("Finish all constructions for 2 gold").

It shouldn't cost me 2 gold WHEN I try to instantly finish building a palace or residence. 

Do you understand it?

![naamloos](https://f.cloud.github.com/assets/2157530/907261/9ec07d6a-fd22-11e2-95c1-4db7fd661b11.png)

**Comment by yi12345** [comment]
fixed.
