### ISSUE TITLE
Hero Stats and reset button.

### ISSUE THREAD

**Issue by terrytory** [yi12345/TravianZ#26]
Okay.. Looks like the reset button doesnt work. It "clears" the stats, but the "before" stats are still there.

Example: 
1) I put some points at hero regen.
2) Hit the reset button. 
3) Put everything  at deff
4) The hero has the same regen amount. 

Also, some report that the hero points does not seem to work. However, the regen works, but the deff/off points does not seem to work. 
- Terry

**Comment by yi12345** [comment]
i don't need it, is work fine, how your hero died?

**Comment by terrytory** [comment]
It died at an IronOasis with little troops. :/
