### ISSUE TITLE
Warning: Invalid argument supplied for foreach() in C:\wamp\www\GameEngine\Automation.php on line 4345

### ISSUE THREAD

**Issue by ghost** [yi12345/TravianZ#261]
Warning: Invalid argument supplied for foreach() in C:\wamp\www\GameEngine\Automation.php on line 4345

```
private function regenerateOasisTroops() {
    global $database;
    $time = time();
    $time2 = NATURE_REGTIME;
    $q = "SELECT * FROM " . TB_PREFIX . "odata where conqured = 0 and $time - lastupdated2 > $time2";
    $array = $database->query_return($q);
    foreach($array as $oasis) {
        $database->populateOasisUnits($oasis['wref'],$oasis['high']);
        $database->updateOasis2($oasis['wref']);
    }
}
```

Please help me......

**Comment by Shadowss** [comment]
Put a screen. When apper that error?

**Comment by ghost** [comment]
Sorry...I have no software to take screenshot....but u can see it
but you can download http://www.mediafire.com/?zx2s9cxer6llrz0
and see the Warning is coming in signup page(and login page and a lot of page).

**Comment by yi12345** [comment]
reinstall your server and make sure you doing it with the last update or you can add NATURE_REGTIME to config.

**Comment by ghost** [comment]
Thank
