### ISSUE TITLE
Medals problem

### ISSUE THREAD

**Issue by Shadowss** [yi12345/TravianZ#264]
I test medals.php from this version 100 times and it doesn`t work correctly. I try to figure what`s happend with this system.

Alliance medal works perfectly.

Player medal not works good.

Example : if i update 1,2,3,4,5 weeks you must recive some bonus medals. So this medals don`t recived.

It works correctly this part : 

-Top 10 Attacker<br />
-Top 10 Defender<br />
-Top 10 Robbers<br />
-Top 10 Alliance Attacker<br />
-Top 10 Alliance Defencer<br />
-Top 10 Alliance Robbers<br />
-Top 10 Alliance Climbers(Rank)<br />
-Top 10 Pop Climbers<br />
-Top 10 Rank Climbers<br />
-Bonus: Attacker AND Defender<br />

After this part you must to recive : 

-Bonus: 3/5/10 times in a row top 3 Pop Climbers<br />
-Bonus: 3/5/10 times in a row top 3 Rank Climbers<br />
-Bonus: 3/5/10 times top 3 Attack<br />
-Bonus: 3/5/10 times top 3 Defence<br />
-Bonus: 3/5/10 times top 3 Robber<br />

-Bonus: 3/5/10 times in a row top 10 Attack<br />
-Bonus: 3/5/10 times in a row top 10 Defence<br />
-Bonus: 3/5/10 times in a row top 10 Pop Climbers<br />
-Bonus: 3/5/10 times in a row top 10 Rank Climbers<br />
-Bonus: 3/5/10 times in a row top 10 Robber<br />

FOR PLAYERS NOT FOR ALIANCE.

I worked to this part of code and works correctly but i cannot implement last update of yi12345

This is my code : http://pastebin.com/L30A9u5m

**Comment by NarcisRO-RGZ** [comment]
what about starvation?? is it fixed on this version??

**Comment by Shadowss** [comment]
No , i have a script for starvation but not works correctly. If you have negative crop and have crop in warehouse troops die ...
