### ISSUE TITLE
Excessive query count?

### ISSUE THREAD

**Issue by ghost** [yi12345/TravianZ#28]
Right now, when I run it on my VPS, TravianZ makes A LOT of queries to the MySQL database. Considering that it makes around 2k queries/sec and it takes 5-10sec for every page to load (WITH ONLY ONE USER), it makes around 10-20k queries/request, which is inacceptable. Why does this happen?

**Comment by ghost** [comment]
OMG, it adds resources in oases on every pageload! Isn't there any way to make this, for example, run on a cronjob, or something better?

**Comment by yi12345** [comment]
i don't know, sorry about that, but maybe another guy will find better way to do it.

**Comment by ghost** [comment]
I managed to make it run slightly faster by offloading oases in automation.php, but it's still loading in 2-3 secs. :(
