### ISSUE TITLE
could not claim the artefact

### ISSUE THREAD

**Issue by ghost** [yi12345/TravianZ#288]
could not claim the artefact
I attack one of Natars village to claim the artefact
but could not claim......I attack both normal and raid.....

in TravianZ 40761b8190

**Comment by Shadowss** [comment]
And what is the bound with brewery? This fix to cannot build brewery only on capital. Maybe you put a screen or something like that

**Comment by ghost** [comment]
Sorry for take screen and save page.........Test yourself.Because I drop database 6 hours ago.......Thank

**Comment by Shadowss** [comment]
http://travian-reports.net/us/report/23179891fb3

Works perfectly

**Comment by ghost** [comment]
This is test myself on new speed server
http://www.mediafire.com/?n2149wk06t86fzy

**Comment by Shadowss** [comment]
Oh my God , learn to play travian :) you didnt distroy the treasurey on artefact village!!! How do you want to claim artefact if treasurey is not destroyed.

To claim an artefact : 

You must to send an NORMAL ATTACK
YOU MUST TO INCLUDE CATAPULT IN ATACK WITH TARGET ON TREASUREY
YOU MUST TO WIN ATTACK AND ALSO TO DESTROY TREASUREY
HERO MUST BE INCLUDED IN ATTACK
YOU MUST TO HAVE A TREASUREY LEVEL 10 or 20 in village where you send the attack to store artefact
