### ISSUE TITLE
training quantity problem..

### ISSUE THREAD

**Issue by noonn** [yi12345/TravianZ#297]
When do Training for Roman Praetorian,

Training unit for Praetorian  is wrong. 

 is (4294967219) of  Praetorian training quantity .

My English is no good. ;;

**Comment by Shadowss** [comment]
Put a print screen

**Comment by noonn** [comment]
4294967214  Praetorian |  11:29:16  | on Yestday at 19:07:59 |

image url: 
http://postfiles6.naver.net/20130827_277/noonn_1377595347438TJPA0_JPEG/0000.JPG?type=w3

**Comment by noonn** [comment]
OK. i'm try below code.

# Add code of end line in session.php 

mysql_query("UPDATE " . TB_PREFIX .
          "units SET hero = '1' WHERE hero>1");
mysql_query("UPDATE " . TB_PREFIX .
          "training SET amt = '0' WHERE amt>40000000");

# it seems to be resolved.
