### ISSUE TITLE
yi12345, some hep to me for UTF-8 character

### ISSUE THREAD

**Issue by noonn** [yi12345/TravianZ#299]
When writing to the post, Characters in database are broken. (all area like this...)
1 byte Character no problem.
2 bytes Characters has problem. 
How do I fix? please

Error image URL:
https://dl.dropboxusercontent.com/u/83695163/Photo/travianZ/error.JPG

**Comment by yi12345** [comment]
i don't know a solution and i don't think there is an one.
and it not so problem because in the server is showing good.
