### ISSUE TITLE
i need to new what The requirements to run script 

### ISSUE THREAD

**Issue by Foxuae** [yi12345/TravianZ#30]
hi 
how are i want to knew The requirements to run script

Because i can't install the script like Before

you can Try to install For you 
http://welduae.net/hh/install

**Comment by ghost** [comment]
If it doesn't work, there's obviously a problem with your server. Can you check your PHP error log?

**Comment by Foxuae** [comment]
php error log

[Mon May 21 17:08:33 2012] [error] [client 121.247.175.176] File does not exist: /home/weldnet/public_html/hh/install/new.js, referer: http://welduae.net/hh/install/ [Mon May 21 17:08:33 2012] [error] [client 121.247.175.176] File does not exist: /home/weldnet/public_html/404.shtml, referer: http://welduae.net/hh/install/ [Mon May 21 17:08:33 2012] [error] [client 121.247.175.176] File does not exist: /home/weldnet/public_html/hh/install/img, referer: http://welduae.net/hh/install/ [Mon May 21 17:08:33 2012] [error] [client 121.247.175.176] File does not exist: /home/weldnet/public_html/404.shtml, referer: http://welduae.net/hh/install/

**Comment by ghost** [comment]
Seems to work fine right now. Refreshing the page made it load

**Comment by yi12345** [comment]
all those errors are host or connection problems, not problem in files.

**Comment by Foxuae** [comment]
sit not working
check 
http://welduae.net/hh/install/ :(

**Comment by ghost** [comment]
server problems, I just checked and the script works on my server

**Comment by yi12345** [comment]
change to another host (paid is recommened), it will help you.

**Comment by Foxuae** [comment]
ok can you Give I good Host $$$

**Comment by yi12345** [comment]
i don't know, try to ask somewhere or search
edit: is work now, try to install (i think you need to play with the back and next buttons (of your browser) and the next button of the install). if this will faild, change host.

**Comment by ghost** [comment]
Foxuae, I can help you find a good host and help you set it up just the right way, if you want (I have experience) please email me: bogdacutu at robamb.co.cc

**Comment by Foxuae** [comment]
i find the problem
For CCS in your File
i try to insttall Used The Bowser Google Chrome is Going Fine But With Mozilla Firefox And Internet Explorer we Cant Install

**Comment by ghost** [comment]
I tested, it didn't work on Google Chrome either. You just have a very crappy host.
