### ISSUE TITLE
Update to TOP 10 error

### ISSUE THREAD

**Issue by noonn** [yi12345/TravianZ#301]
error message as below:

Warning: mysql_num_rows(): supplied argument is not a valid MySQL result resource in /home/diyworld/public_html/diyworld/travian/medals.php on line 135

Warning: mysql_num_rows(): supplied argument is not a valid MySQL result resource in /home/diyworld/public_html/diyworld/travian/medals.php on line 135

Warning: mysql_num_rows(): supplied argument is not a valid MySQL result resource in /home/diyworld/public_html/diyworld/travian/medals.php on line 211

Warning: mysql_num_rows(): supplied argument is not a valid MySQL result resource in /home/diyworld/public_html/diyworld/travian/medals.php on line 211

Warning: mysql_num_rows(): supplied argument is not a valid MySQL result resource in /home/diyworld/public_html/diyworld/travian/medals.php on line 362

Warning: mysql_num_rows(): supplied argument is not a valid MySQL result resource in /home/diyworld/public_html/diyworld/travian/medals.php on line 362

Warning: mysql_num_rows(): supplied argument is not a valid MySQL result resource in /home/diyworld/public_html/diyworld/travian/medals.php on line 437

Warning: mysql_num_rows(): supplied argument is not a valid MySQL result resource in /home/diyworld/public_html/diyworld/travian/medals.php on line 437

error code line -> while(mysql_num_rows(mysql_query($query2)) > 0 && $i > 0){ 

How to fix?

**Comment by noonn** [comment]
This line is *.txt.

**Comment by kisserlb** [comment]
Treasury  Small artefacts | Large artefacts are NOT shown when WWW village are shown

**Comment by kisserlb** [comment]
Treasury  Small artefacts | Large artefacts are NOT shown when WWW village are shown  ****

**Comment by Shadowss** [comment]
Put a IMAGE SCREEN !!!
