### ISSUE TITLE
TRANSLATION to PT

### ISSUE THREAD

**Issue by eliopinho** [yi12345/TravianZ#311]
hello mate.. 
i want help you in translation of your travianZ to PT portuguese

i translate te file en.php located in /GameEngine/Lang
but this file only translates a little bit of the game, 

do you please point me the right files to translate of the whole game, and after i do it i will share with you the translation on case of you want include in your work..

**Comment by v2al4global** [comment]
I am also in the same case translate /GameEngine/lang for pt-br, however it happens, the game is not fully translated much is still in English, @eliopinho could translate some other parts in /Templates, tpl files have things to translate what I've seen here, more would be nice if someone speaks or @yi12345 to the right places or names and locations of files that have a million things to translate, I also intend to provide my translation to br Here^ ^, Vlw.

**Comment by Shadowss** [comment]
This script have 10000 bugs and people think to translate. People this script need developers not translators

**Comment by yi12345** [comment]
the script have some bugs, but is working ok in most functions, and even 100% on the basics (at least for me).
about the translate you have to change some text in the root files but most of the text is on templates folder.
and i don't need this translate because it will replace the english.
