### ISSUE TITLE
[fix] characters can be entered

### ISSUE THREAD

**Issue by noonn** [yi12345/TravianZ#316]
When send troop,
Special characters can be entered
So, the troop is sent.

Fix -> added source in units.php
## find code and added code

if(isset($post['t'.$i]))
{
.
.
.
.
.
.

if(preg_match('/[^0-9]/',$post['t'.$i]))  //added code
 {
 $form->addError("error","Special characters can't entered");
 break;
}

 if ($post['t11'] > $village->unitarray['hero'])
{
.
.
.
.
.

if(preg_match('/[^0-9]/',$post['t11']))  //added code
 {
 $form->addError("error","Special characters can't entered");
 //break;
 }

---

error Image link:
http://postfiles2.naver.net/20130915_257/noonn_1379204177659Kdxon_JPEG/troopsend.jpg?type=w3 

added code image link:
http://postfiles10.naver.net/20130915_89/noonn_137920963642455KRv_JPEG/addedcode.jpg?type=w3

**Comment by yi12345** [comment]
thanks, fixed.
