### ISSUE TITLE
[MOD] Daily get 1 gold

### ISSUE THREAD

**Issue by noonn** [yi12345/TravianZ#317]
My English no good. ^^

I made it.

Description:
Daily bonus gold every day, one can be obtained.
Please see the link below the image.
Work is perfect.
Trying to get users to get gold seems to be more visit.

Have a nice day.

// **\* Added DB ***

ALTER TABLE s1_users 
ADD `dailygold` tinyint(1) unsigned NOT NULL DEFAULT '0', 
ADD `dailygoldtime` int(11) unsigned NOT NULL DEFAULT '0'; 

// **\* Added travian/Templates/menu.tpl ***

<img src="https://dl.dropboxusercontent.com/u/83695163/Photo/travianZ/1212.GIF">

// **\* make file: travian/dailygold.php

Download link the dailygold.php
https://dl.dropboxusercontent.com/u/83695163/Photo/travianZ/dailygold.php

---

Image link (Daily bonus menu click)
http://postfiles15.naver.net/20130915_62/noonn_13792113852891wXOI_JPEG/01.jpg?type=w3

Image link (Won 1 gold)
http://postfiles5.naver.net/20130915_148/noonn_1379211385949LbFIe_JPEG/03.jpg?type=w3

Image link (Already won 1 gold)
http://postfiles10.naver.net/20130915_137/noonn_1379211387115hppfY_JPEG/04.jpg?type=w3

Image link (Bonus time After 1 day)
http://postfiles1.naver.net/20130915_112/noonn_1379211385597dOQ4h_JPEG/02.jpg?type=w3

**Comment by yi12345** [comment]
not bad, but i don't wan't this here, you can use it in your server and upload this in another site for who wants.

**Comment by noonn** [comment]
I hope those who want Once have used.

**Comment by izzat317** [comment]
where to upload it ?
