### ISSUE TITLE
Bug 10 from list , attaks on large map

### ISSUE THREAD

**Issue by Shadowss** [yi12345/TravianZ#324]
This is the part of code that must be implemented to work that function , must be implemented in mapviewlarge.tpl

Bug 10 : If you have plus account activated you cannot see the attck/deff/scout images when you attack a village (i mean img on villages : red swords etc..)

Screen : http://i43.tinypic.com/2wd8pzd.jpg

Solution but must be implemented :

```
    $vid = $maparray[$index]['id'];
    $incoming_attacks = $database->getMovement(3,$vid,1);
    $att = '';

    if (count($incoming_attacks) > 0) {
        $inc_atts = count($incoming_attacks);
            if($incoming_attacks[$i]['attack_type'] == 2) {
                $inc_atts -= 1;
            }
        if($inc_atts > 0) {
            $att = '<img style="margin-right:45px;" class="att1" src="img/x.gif" />';
        }
    }

if(!$maparray[$index]['fieldtype'] && $maparray[$index]['oasistype'] && $maparray[$index]['occupied']){
    $occupied = "-s";
}else{ $occupied = ""; }
echo "<a href=\"karte.php?d=".$maparray[$index]['id']."&c=".$generator->getMapCheck($maparray[$index]['id'])."\" style=\"cursor:deLumberult;\"><div class=\"tile tile-".$i."-row".$row1." ".$image."".$occupied."\" title=\"".$targettitle."\">";
if($session->plus) {
echo $att;
}
echo "</div></a>\n";

if($i == 8 || $i == 17 || $i == 26 && $row1 <= 5) {
    $row1 += 1;
}
$index+=1;
```

**Comment by yi12345** [comment]
what to do with this code?

**Comment by Shadowss** [comment]
Look on bug 10 on the list , http://forum.ragezone.com/f742/travianz-official-yi12345-bugs-list-952593/ this code fix bug 10 but must be implemented. It`s implemented only on T4 version but it`s also a T3.6 function

**Comment by yi12345** [comment]
is should be only in the large map?

**Comment by Shadowss** [comment]
Yes only in large map , it`s a plus function

**Comment by yi12345** [comment]
and it works on t4? you sure that only this code is what missing for make it good on t3?

**Comment by Shadowss** [comment]
Advocaite says this is the code . I don`t have an T4 instaled on my pc i`ll test now

**Comment by yi12345** [comment]
i will try to use it, but on t3 the map code is different so i don't sure that i will do it.

**Comment by Shadowss** [comment]
I will speak with him , will see , if you have any ideea about troops adding on reinforcements 

Error appers in here : http://img692.imageshack.us/img692/1756/zyl6.png

@yi12345 : read here : http://forum.ragezone.com/f741/help-bug-10-travianz-list-958934/
