### ISSUE TITLE
Improved view in the rally point.

### ISSUE THREAD

**Issue by Shadowss** [yi12345/TravianZ#334]
It`s a simple improvements can be coded ?

IMG : http://travian.shadowss.ro/gpack/travian_default/img/p/attack_marker.gif

And also sort on messages : Sorting function for reports and messages

IMG : http://travian.shadowss.ro/gpack/travian_default/lang/en/p/sort.jpg

**Comment by noonn** [comment]
You try address as below.
travian/nachrichten.php?s=-10&o=0

-10 bug. ^^

**Comment by Shadowss** [comment]
:)) haha works but not appers nothing

**Comment by noonn** [comment]
haha That's right. not appers nothing
