### ISSUE TITLE
Wall img on spy report for each tribe

### ISSUE THREAD

**Issue by Shadowss** [yi12345/TravianZ#356]
@yi12345 : can you make this code work for each tribe ? I try to implement a code on spy report for view different wall image for each tribe but appers only natar wall after else

I see not show all code it is putted on pastebin. Maybe you can correct to work for each tribe 

Link to pastebin : http://pastebin.com/PhedWqm1

```
    /**************************
        City Wall by Shadow
    **************************/

           if($session->userinfo['tribe'] == 1) {
                $walltitle = 'City Wall';
                $iconClass = 'gebIcon g3' . $tribe . 'Icon';
            } else if($session->userinfo['tribe'] == 2) {
                $walltitle = 'Earth Wall';
                $iconClass = 'gebIcon g3' . $tribe . 'Icon';
            } else if($session->userinfo['tribe'] == 3) {
                $walltitle = 'Palisade';
                $iconClass = 'gebIcon g3' . $tribe . 'Icon';
            }
            else
            {
                /**
                 * @Natar Wall should be called, also using City Wall for the icon for now
                 */
                $walltitle = "Natar Wall";
                $iconClass = 'gebIcon g31Icon';
            }
```

$palaceimg = "<img src=\"".GP_LOCATE."img/g/g26.gif\" height=\"20\" width=\"15\" alt=\"Palace\" title=\"Palace\" />";
$crannyimg = "<img src=\"".GP_LOCATE."img/g/g23.gif\" height=\"20\" width=\"15\" alt=\"Cranny\" title=\"Cranny\" />";
$wallimg = "<img class=\"" . $iconClass . "\" src=\"img/x.gif\" height=\"20\" width=\"15\" alt=\"Wall\" title=\"".$walltitle."\" />";
                $info_spy = "".$spy_pic.",".$palaceimg." Residance/Palace Level : ".$rplevel."

```
            <br>".$crannyimg." Cranny level: ".$crannylevel."<br>".$wallimg." ".$walltitle." : ".$walllevel."";
```

**Comment by yi12345** [comment]
i asked you before, but you said you have no images for antoher tribes.

**Comment by Shadowss** [comment]
I found image 2 days ago for each tribe

**Comment by yi12345** [comment]
so post the links

**Comment by Shadowss** [comment]
http://travian.shadowss.ro/gpack/travian_default/img/g/icon/g31Icon.gif

http://travian.shadowss.ro/gpack/travian_default/img/g/icon/g32Icon.gif

http://travian.shadowss.ro/gpack/travian_default/img/g/icon/g33Icon.gif

Img for each tribe

**Comment by yi12345** [comment]
thanks, fixed
