### ISSUE TITLE
Battle bug problem

### ISSUE THREAD

**Issue by Shadowss** [yi12345/TravianZ#366]
This is the travian reports : http://travian-reports.net/us/report/23627461c46

And this is the troops remain after attack :

Troops:
Spearman    25666   Spearman
Axeman  247 Axeman
Paladin 3873    Paladin
Teutonic Knight 247 Teutonic Knight

Attack was RAID! , because catapult doesnt fire

**Comment by yi12345** [comment]
so what the problem? in raid not all troops die

**Comment by Shadowss** [comment]
Lol but why die only one category of troop. Report doesn't apper correctly. In report apper something after battle in rally point apper something.

**Comment by Shadowss** [comment]
The problem is on defender not on attacker

**Comment by Shadowss** [comment]
Also it`s not a battle report it`s a Report problem in Templates/Notice

**Comment by noonn** [comment]
There is an error for reconnaissance.
Scouts are not good.

**Comment by Shadowss** [comment]
Have anyone a solution ?!
