### ISSUE TITLE
Big bug with quests

### ISSUE THREAD

**Issue by Shadowss** [yi12345/TravianZ#378]
Watch video in here : http://www.youtube.com/watch?v=qzIxx8coLYo

**Comment by noonn** [comment]
Huk
this  is  bug ㅠㅠ

**Comment by Shadowss** [comment]
:))

**Comment by noonn** [comment]
Did you fixed quest_core bug?

**Comment by Shadowss** [comment]
No ... i dont know how to do that. From quest 17 upgrade your warehouse dont work correctly , it is decalated with 1

**Comment by noonn** [comment]
First quest bug will issue tomorrow method.
i am try  effort for quest bug.
