### ISSUE TITLE
Populate Oasis

### ISSUE THREAD

**Issue by jirimedved** [yi12345/TravianZ#38]
Hi,

in functions populateOasisUnitsHigh() in db_MYSQL.php is :

$q2 = "SELECT \* FROM " . TB_PREFIX . "wdata where oasistype != 0";
$result2 = mysql_query($q2, $this->connection);
while($row = mysql_fetch_array($result2)) {
    $wid = $row['id'];
    $basearray = $this->getMInfo($wid);
    switch($basearray['oasistype']) {
        ...
    }
}

Maybe better:

$q2 = "SELECT \* FROM " . TB_PREFIX . "wdata where oasistype != 0";
$result2 = mysql_query($q2, $this->connection);
while($row = mysql_fetch_array($result2)) {
    $wid = $row['id'];
    switch($row['oasistype']) {
        ...
    }
}

**Comment by yi12345** [comment]
changed.
