### ISSUE TITLE
creation of troops immediately terminate

### ISSUE THREAD

**Issue by MaxMad** [yi12345/TravianZ#41]
hi friend, as you can add in the bonus menu function to end the production line of troops through gold?

thanks for your daily efforts :)

**Comment by yi12345** [comment]
no, sorry, i don't want to add it.
travianz going to be like official server.

**Comment by MaxMad** [comment]
use the speed that the game is necessary, since queues are arming more than 48 hours of troops, Thank him tell me how to do it brother
