### ISSUE TITLE
Catapult

### ISSUE THREAD

**Issue by gamerx159** [yi12345/TravianZ#45]
Hi again, maybe you can fix catapult? Because I set target to demolish Treasure, but they demolish with random target ..

And wtf??
Your hero could not claim the artefact and gained 0 XP from the battle.

**Comment by gamerx159** [comment]
Your hero could not claim the artefact and gained 0 XP from the battle. - fix :D

And Quest don't work

**Comment by yi12345** [comment]
if you attacked natars is because the artefact of cranny + random aim.

about "hero could not claim the artefact and gained 0 XP from the battle" i will fix.
and the quest is because your host.
