### ISSUE TITLE
Fix for Horse Drinking Trough

### ISSUE THREAD

**Issue by jirimedved** [yi12345/TravianZ#46]
Hi,

i have fix:

in GameEngine/Technology.php

if(isset($horsedrinking)){
if(($i==4 && $buildarray['f'.$horsedrinking] >= 10)
|| ($i==5 && $buildarray['f'.$horsedrinking] >= 15)
|| ($i==6 && $buildarray['f'.$horsedrinking] == 20)) {
$upkeep += ($dataarray['pop']-1) \* $array[$unit];
} else {
$upkeep += $dataarray['pop'] \* $array[$unit];
}}else{
$upkeep += $dataarray['pop'] \* $array[$unit];
}

**Comment by yi12345** [comment]
thanks.
