### ISSUE TITLE
the wonders

### ISSUE THREAD

**Issue by MaxMad** [yi12345/TravianZ#48]
hi friend, who may be you can not see the wonders, are in statistics, but when you click on it goes
replace files that have newer, and does the same
Warning: mysql_fetch_array() expects parameter 1 to be resource, boolean given in /home/ts1travi/public_html/T3.6/GameEngine/Database/db_MYSQL.php on line 688

Warning: mysql_fetch_assoc() expects parameter 1 to be resource, boolean given in /home/ts1travi/public_html/T3.6/Templates/Map/vilview.tpl on line 6
 (|)

**Comment by yi12345** [comment]
i didn't see any problem. try to explain more, if you can give an image it will be good.

**Comment by MaxMad** [comment]
When I click here
http://img232.imageshack.us/img232/9282/13465833.jpg
the screen is so
http://img29.imageshack.us/img29/1303/17179955.jpg

**Comment by yi12345** [comment]
try with the new version, maybe fixed now.

**Comment by MaxMad** [comment]
just downloaded, I have to update something?

**Comment by yi12345** [comment]
i reccomened to reinstall, but for this problem i don't think that you need.

**Comment by MaxMad** [comment]
thanks friend, I install, I'll go see the errors and I'm still commenting.
now the error is found in login.php, which always
The SERVER STARTS NOW
solve it, replacing it with another login.php yours I had before
I can you tell me how the show, to see them
