### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by gamerx159** [yi12345/TravianZ#49]
Hi again. :)
Parse error: syntax error, unexpected T_VARIABLE in /home/zuikyys/public_html/s1/GameEngine/BBCode.php on line 1

I have a problem with this code, when i want to read letter, throws this error.

**Comment by gamerx159** [comment]
same problem in ally forum..

P.S when i delete BBcode.php all work almost perfectly.

**Comment by yi12345** [comment]
about message i think you need to download my newest version and reinstall your server, and now you will got "[message]" in the start of every message and "[/message]" in the end (you can try to add this in the database to check if works).
the bbcode of forum fixed too now.

**Comment by gamerx159** [comment]
http://www.part.lt/img/c6c24b428c3846900e72c6d515c200bb935.JPG
Newest Version, when i want read multihunter letter
