### ISSUE TITLE
magic_quotes_gpc = Off

### ISSUE THREAD

**Issue by MaxMad** [yi12345/TravianZ#52]
where I have to look for that brother?
find 'magic_quotes_gpc = Off' and replace with 'magic_quotes_gpc = On' for better options with special characters (you need to restart your appache and mysql for make this change affective

**Comment by yi12345** [comment]
in php.ini

**Comment by MaxMad** [comment]
php.ini is in the hosting?

**Comment by yi12345** [comment]
i don't know, ask someone
