### ISSUE TITLE
please add this file in Templates\Build

### ISSUE THREAD

**Issue by MaxMad** [yi12345/TravianZ#57]
16_incomming.tpl
your file is 
201                     echo "at ".$datetime[1]."</div>";
please add this
201                 echo "at ".$datetime[1]." hours</div>";

Thanks again for your day job!

Maximiliano (Argentina)

**Comment by yi12345** [comment]
changed, thanks.

**Comment by MaxMad** [comment]
also please change this line in
templates/build/16_99.tpl
line 78 
<div class="clear"></div><p><input type="image" value="ok" name="s1" id="btn_ok" class="dynamic_img" src="img/x.gif" tabindex="8" alt="OK" <?php if(!$market->merchantAvail()) { echo "DISIABLE"; }?>/></p></form>
change DISIABLE to ENABLE
to work evasion attacks

thanks broder

**Comment by yi12345** [comment]
i deleted it, is uneeded

**Comment by MaxMad** [comment]
on my server that my friends are playing your version, use it much, plus it makes to spend their gold :D

**Comment by yi12345** [comment]
not the evasion, the line.

**Comment by MaxMad** [comment]
ah ok.
Please add this (in) in file Templates\Building.tpl
your file is
45  span id=\"timer".$timer."\">";
please modific to
45    in span id=\"timer".$timer."\">";

**Comment by yi12345** [comment]
changed. for what this?

**Comment by MaxMad** [comment]
not because I can not copy the row here
I hope you can see it here
http://img845.imageshack.us/img845/2880/templatesbuldingtpl.jpg
mine is in Spanish, so you replace (en) for (in) in line 45 please

thanks brother :D

**Comment by yi12345** [comment]
changed, thanks.
