### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by MaxMad** [yi12345/TravianZ#58]
I get this message all the time and I have the blank page, I have people playing and I can not restart, I need another solution brother

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 's village 3 village decided to join your empire.,,,0,0,0,0,,',1340528836,0)' at line 1

**Comment by yi12345** [comment]
download my version again (without reinstall) and it should to work.

**Comment by MaxMad** [comment]
then replace all the files on the server with the new low? not affect users?

**Comment by MaxMad** [comment]
solved
Replace the file Automation.php
on the newly upgraded and gave me more errors, I replaced the old and now is fine.

Thank you for your attention and dedication to improve every day this scrip
