### ISSUE TITLE
Gold bug

### ISSUE THREAD

**Issue by gamerx159** [yi12345/TravianZ#60]
Hey need help agen. Wen 1 player pays 2gold to complete construction orders all server players buildings finishes building too.
Any idea how to fix it?

**Comment by yi12345** [comment]
is fixed long time ago, download my last version.

**Comment by gamerx159** [comment]
Oh realy? I use last version.

**Comment by yi12345** [comment]
i don't know, i checked the code and it need to be in your village only.
