### ISSUE TITLE
Troops training halted

### ISSUE THREAD

**Issue by AresLex** [yi12345/TravianZ#61]
Hi Yi. Thanks again for the tremendous effort you've put in.

Server speed: 500x

When i train troops greater than 10,000 it shows a completion time within 02h42m48s.
However when left overnight, the troops training has not complete and the counter is now increasing in duration.
Troop training has now taken more than 12hours.

Please have a look. Thank you.

**Comment by yi12345** [comment]
i think you haven't the newest file. the problem was because i changed the training. try to download my version again and reinstall your server.
tell me if it works after that.

**Comment by AresLex** [comment]
Downloaded the newer version and it now works.

Thank you and keep up the good work!

**Comment by AhmedMesbah** [comment]
How to have an option to cancel trained troops?

I have a big problem showing 1548111845191 Clubswinger being trained, anyway to fix?
