### ISSUE TITLE
Problem install

### ISSUE THREAD

**Issue by Mimi93** [yi12345/TravianZ#68]
Warning: include(../GameEngine/config.php) [function.include]: failed to open stream: No such file or directory in /home/playin/domains/playinedit.ro/public_html/GameEngine/Admin/database.php on line 23

Warning: include(../GameEngine/config.php) [function.include]: failed to open stream: No such file or directory in /home/playin/domains/playinedit.ro/public_html/GameEngine/Admin/database.php on line 23

Warning: include() [function.include]: Failed opening '../GameEngine/config.php' for inclusion (include_path='.:/usr/local/lib/php') in /home/playin/domains/playinedit.ro/public_html/GameEngine/Admin/database.php on line 23

Warning: include(../GameEngine/Data/buidata.php) [function.include]: failed to open stream: No such file or directory in /home/playin/domains/playinedit.ro/public_html/GameEngine/Admin/database.php on line 24

Warning: include(../GameEngine/Data/buidata.php) [function.include]: failed to open stream: No such file or directory in /home/playin/domains/playinedit.ro/public_html/GameEngine/Admin/database.php on line 24

Warning: include() [function.include]: Failed opening '../GameEngine/Data/buidata.php' for inclusion (include_path='.:/usr/local/lib/php') in /home/playin/domains/playinedit.ro/public_html/GameEngine/Admin/database.php on line 24

Warning: Cannot modify header information - headers already sent by (output started at /home/playin/domains/playinedit.ro/public_html/GameEngine/Admin/database.php:23) in /home/playin/domains/playinedit.ro/public_html/install/include/oasis.php on line 19

**Comment by jsemErOoR** [comment]
Warning: include(../GameEngine/config.php) [function.include]: failed to open stream: No such file or directory in /data/web/virtuals/12846/virtual/www/subdom/beta/GameEngine/Admin/database.php on line 23

Warning: include(../GameEngine/config.php) [function.include]: failed to open stream: No such file or directory in /data/web/virtuals/12846/virtual/www/subdom/beta/GameEngine/Admin/database.php on line 23

Warning: include() [function.include]: Failed opening '../GameEngine/config.php' for inclusion (include_path='.:/data/web/virtuals/12846/virtual') in /data/web/virtuals/12846/virtual/www/subdom/beta/GameEngine/Admin/database.php on line 23

Warning: include(../GameEngine/Data/buidata.php) [function.include]: failed to open stream: No such file or directory in /data/web/virtuals/12846/virtual/www/subdom/beta/GameEngine/Admin/database.php on line 24

Warning: include(../GameEngine/Data/buidata.php) [function.include]: failed to open stream: No such file or directory in /data/web/virtuals/12846/virtual/www/subdom/beta/GameEngine/Admin/database.php on line 24

Warning: include() [function.include]: Failed opening '../GameEngine/Data/buidata.php' for inclusion (include_path='.:/data/web/virtuals/12846/virtual') in /data/web/virtuals/12846/virtual/www/subdom/beta/GameEngine/Admin/database.php on line 24

Warning: Cannot modify header information - headers already sent by (output started at /data/web/virtuals/12846/virtual/www/subdom/beta/GameEngine/Admin/database.php:23) in /data/web/virtuals/12846/virtual/www/subdom/beta/install/include/oasis.php on line 19

**Comment by jsemErOoR** [comment]
I have this same problem, and chmod folder install have 777, files on folder install have chmod 777. GameEngine chmod 777 have

**Comment by yi12345** [comment]
you deleted all tables from mysql? do it and than install your server.

**Comment by jsemErOoR** [comment]
i haved new database, so not tables on myslq

**Comment by Mimi93** [comment]
Who can help me if I give ID in TeamViewer, to install the script on my website?

**Comment by yi12345** [comment]
try to replace "../GameEngine/Data/buidata.php" with "../../GameEngine/Data/buidata.php" and "../GameEngine/config.php" with "../../GameEngine/config.php", and return it back after finish install.

**Comment by Mimi93** [comment]
Ok . Thanks

**Comment by Mimi93** [comment]
do you want to help me with team viewer?

**Comment by Mimi93** [comment]
Skype: mihai.lasconi  

Yahoo: mihai_mimi93

**Comment by yi12345** [comment]
i don't know about that, so i can't help, sorry.

**Comment by Mimi93** [comment]
Eventually I managed to install, but would like some advice. Www.playinedit.ro Why work so hard? stupid host? if so, what hosting can have for free and to be as good as? and if no one with money.

**Comment by Mimi93** [comment]
It is an error with the map can not look for her players: |
