### ISSUE TITLE
don´t work page loading (on to chmod 644 GameEngine)

### ISSUE THREAD

**Issue by jsemErOoR** [yi12345/TravianZ#69]
Warning: include(GameEngine/Account.php) [function.include]: failed to open stream: Permission denied in /data/web/virtuals/12846/virtual/www/subdom/beta/login.php on line 15

Warning: include(GameEngine/Account.php) [function.include]: failed to open stream: Permission denied in /data/web/virtuals/12846/virtual/www/subdom/beta/login.php on line 15

Warning: include() [function.include]: Failed opening 'GameEngine/Account.php' for inclusion (include_path='.:/data/web/virtuals/12846/virtual') in /data/web/virtuals/12846/virtual/www/subdom/beta/login.php on line 15

Notice: Undefined variable: session in /data/web/virtuals/12846/virtual/www/subdom/beta/Templates/menu.tpl on line 13

Notice: Trying to get property of non-object in /data/web/virtuals/12846/virtual/www/subdom/beta/Templates/menu.tpl on line 13

Notice: Use of undefined constant HOME - assumed 'HOME' in /data/web/virtuals/12846/virtual/www/subdom/beta/Templates/menu.tpl on line 29
HOME 
Notice: Use of undefined constant LOGIN - assumed 'LOGIN' in /data/web/virtuals/12846/virtual/www/subdom/beta/Templates/menu.tpl on line 29
LOGIN 
Notice: Use of undefined constant REG - assumed 'REG' in /data/web/virtuals/12846/virtual/www/subdom/beta/Templates/menu.tpl on line 29
REG

Notice: Use of undefined constant COMMENCE - assumed 'COMMENCE' in /data/web/virtuals/12846/virtual/www/subdom/beta/login.php on line 58

Notice: Use of undefined constant COOKIES - assumed 'COOKIES' in /data/web/virtuals/12846/virtual/www/subdom/beta/login.php on line 66
COOKIES

Notice: Use of undefined constant START_DATE - assumed 'START_DATE' in /data/web/virtuals/12846/virtual/www/subdom/beta/login.php on line 68

Server will start in:

Notice: Undefined variable: form in /data/web/virtuals/12846/virtual/www/subdom/beta/login.php on line 309

Fatal error: Call to a member function getError() on a non-object in /data/web/virtuals/12846/virtual/www/subdom/beta/login.php on line 309

**Comment by jsemErOoR** [comment]
GameEngine chmod: 644, folder Prevention & Notes on GameEngine folder have chmod 777, when i change chmod on 750 work, but server is verry verry slow loading and i have verry verry good hosting.

Max. nummer PHP process 10
Database    2 GB
PHP memory_limit \*   256 MB
PHP upload_max_filesize  128 MB
PHP post_max_size   128 MB
(http://hosting.wedos.com/cs/webhosting.html) NoLimit + (http://hosting.wedos.com/cs/webhosting/extra.html) NoLimit Extra hosting, oldes (i testing Travianz 3 months back and work verry verry fast, but now is verry verry slow)

**Comment by yi12345** [comment]
is permission problem, not script problem.

**Comment by jsemErOoR** [comment]
So what have make?

**Comment by yi12345** [comment]
give 777 permissions.
if you can't, i don't know what you should to do.
