### ISSUE TITLE
revive hero?

### ISSUE THREAD

**Issue by Dylan96** [yi12345/TravianZ#71]
if the hero dies in battle, can not be revived...

**Comment by yi12345** [comment]
as attacker or defender? because i tested as attacker and you can.

**Comment by Dylan96** [comment]
strange, when he dies attacking, remains "alive" in the dwelling of the hero, but you can not use in battle and nothing happens if you try to revive him

**Comment by yi12345** [comment]
you can try to reinstall your server with the last files?
because for me is works good so is maybe your problem.

**Comment by Dylan96** [comment]
Ok, i'll try :)

**Comment by yi12345** [comment]
tell me if it works for you now.

**Comment by Dylan96** [comment]
Now it works fine :)
