### ISSUE TITLE
what is Evasion?:D

### ISSUE THREAD

**Issue by gamerx159** [yi12345/TravianZ#75]
What mean Evasion? :) And what he doing the server?

**Comment by gamerx159** [comment]
And where i can find messages, when ppls write? This is Support system.

**Comment by yi12345** [comment]
evasion is send troops when got an attack (if you have goldclub and use it for the attacked village), 2 gold for every evasion.
is good for farm that want to train a big army.
about support system i can't help you because i didn't created it, tested it or have a time to test it.

**Comment by gamerx159** [comment]
In 100x speed and 15x troops spped, what evasion how much need?

**Comment by yi12345** [comment]
you can select it on "evasion speed": for speed of x1 is send troops 180 seconds away from the village, for speed of x2 is send troops 90 seconds away from the village, etc.
