### ISSUE TITLE
i can't login ><

### ISSUE THREAD

**Issue by andrew1234** [yi12345/TravianZ#76]
Warning: mysql_fetch_assoc() expects parameter 1 to be resource, boolean given in /home/privatet/public_html/GameEngine/Automation.php on line 818

Warning: Invalid argument supplied for foreach() in /home/privatet/public_html/GameEngine/Automation.php on line 565

Warning: Invalid argument supplied for foreach() in /home/privatet/public_html/GameEngine/Automation.php on line 3793

Warning: Invalid argument supplied for foreach() in /home/privatet/public_html/GameEngine/Automation.php on line 849

Fatal error: Maximum execution time of 30 seconds exceeded in /home/privatet/public_html/GameEngine/Automation.php on line 3470

this error came when i change from travianx > to travianz 
and the automation.php is same with you have now

**Comment by andrew1234** [comment]
Warning: mysql_fetch_assoc() expects parameter 1 to be resource, boolean given in /home/privatet/public_html/GameEngine/Automation.php on line 818

Warning: Invalid argument supplied for foreach() in /home/privatet/public_html/GameEngine/Automation.php on line 565

Warning: Invalid argument supplied for foreach() in /home/privatet/public_html/GameEngine/Automation.php on line 3793

Warning: Invalid argument supplied for foreach() in /home/privatet/public_html/GameEngine/Automation.php on line 849

Warning: Invalid argument supplied for foreach() in /home/privatet/public_html/GameEngine/Automation.php on line 3912

Warning: array_keys() expects parameter 1 to be array, boolean given in /home/privatet/public_html/GameEngine/Automation.php on line 275

Warning: Invalid argument supplied for foreach() in /home/privatet/public_html/GameEngine/Automation.php on line 275

Warning: array_keys() expects parameter 1 to be array, boolean given in /home/privatet/public_html/GameEngine/Automation.php on line 275

Warning: Invalid argument supplied for foreach() in /home/privatet/public_html/GameEngine/Automation.php on line 275

Warning: Invalid argument supplied for foreach() in /home/privatet/public_html/GameEngine/Automation.php on line 3782

Warning: Invalid argument supplied for foreach() in /home/privatet/public_html/GameEngine/Automation.php on line 3761

Warning: mysql_fetch_array() expects parameter 1 to be resource, boolean given in /home/privatet/public_html/GameEngine/Database/db_MYSQL.php on line 326

Warning: Invalid argument supplied for foreach() in /home/privatet/public_html/GameEngine/Building.php on line 32

**Comment by gamerx159** [comment]
Reinstall files, and Version :)

**Comment by yi12345** [comment]
yes, is host probles or problem because missing files or missing columns.
reinstall server with the last files should to help.

**Comment by andrew1234** [comment]
can someone teach me how to reinstall without deleteing user data.. ?
i'am just newbie.. 
thank you so much yi :)

**Comment by gamerx159** [comment]
Try delete all files, but don't delete config.php, and then reinstall files, when files updated move config to gameengine folder..
