### ISSUE TITLE
natars

### ISSUE THREAD

**Issue by pedyvirus** [yi12345/TravianZ#78]
i cant add natars
give this errors:
Warning: fopen(GameEngine/Prevention/cleardeleting.txt) [function.fopen]: failed to open stream: No such file or directory in /home/u878815323/public_html/GameEngine/Automation.php on line 322

Warning: fclose(): supplied argument is not a valid stream resource in /home/u878815323/public_html/GameEngine/Automation.php on line 323

Warning: fopen(GameEngine/Prevention/demolition.txt) [function.fopen]: failed to open stream: No such file or directory in /home/u878815323/public_html/GameEngine/Automation.php on line 3705

Warning: fclose(): supplied argument is not a valid stream resource in /home/u878815323/public_html/GameEngine/Automation.php on line 3706

Warning: fopen(GameEngine/Prevention/market.txt) [function.fopen]: failed to open stream: No such file or directory in /home/u878815323/public_html/GameEngine/Automation.php on line 862

Warning: fclose(): supplied argument is not a valid stream resource in /home/u878815323/public_html/GameEngine/Automation.php on line 863

Warning: fopen(GameEngine/Prevention/research.txt) [function.fopen]: failed to open stream: No such file or directory in /home/u878815323/public_html/GameEngine/Automation.php on line 3128

Warning: fclose(): supplied argument is not a valid stream resource in /home/u878815323/public_html/GameEngine/Automation.php on line 3129

Warning: fopen(GameEngine/Prevention/training.txt) [function.fopen]: failed to open stream: No such file or directory in /home/u878815323/public_html/GameEngine/Automation.php on line 3544

Warning: fclose(): supplied argument is not a valid stream resource in /home/u878815323/public_html/GameEngine/Automation.php on line 3545

Warning: fopen(GameEngine/Prevention/starvation.txt) [function.fopen]: failed to open stream: No such file or directory in /home/u878815323/public_html/GameEngine/Automation.php on line 3935

Warning: fclose(): supplied argument is not a valid stream resource in /home/u878815323/public_html/GameEngine/Automation.php on line 3936

Warning: fopen(GameEngine/Prevention/celebration.txt) [function.fopen]: failed to open stream: No such file or directory in /home/u878815323/public_html/GameEngine/Automation.php on line 3683

Warning: fclose(): supplied argument is not a valid stream resource in /home/u878815323/public_html/GameEngine/Automation.php on line 3684

Warning: fopen(GameEngine/Prevention/sendunits.txt) [function.fopen]: failed to open stream: No such file or directory in /home/u878815323/public_html/GameEngine/Automation.php on line 942

Warning: fclose(): supplied argument is not a valid stream resource in /home/u878815323/public_html/GameEngine/Automation.php on line 943

Warning: fopen(GameEngine/Prevention/sendreinfunits.txt) [function.fopen]: failed to open stream: No such file or directory in /home/u878815323/public_html/GameEngine/Automation.php on line 2942

Warning: fclose(): supplied argument is not a valid stream resource in /home/u878815323/public_html/GameEngine/Automation.php on line 2943

Warning: fopen(GameEngine/Prevention/returnunits.txt) [function.fopen]: failed to open stream: No such file or directory in /home/u878815323/public_html/GameEngine/Automation.php on line 3015

Warning: fclose(): supplied argument is not a valid stream resource in /home/u878815323/public_html/GameEngine/Automation.php on line 3016

Warning: fopen(GameEngine/Prevention/settlers.txt) [function.fopen]: failed to open stream: No such file or directory in /home/u878815323/public_html/GameEngine/Automation.php on line 3076

Warning: fclose(): supplied argument is not a valid stream resource in /home/u878815323/public_html/GameEngine/Automation.php on line 3077

Warning: mysql_num_rows(): supplied argument is not a valid MySQL result resource in /home/u878815323/public_html/GameEngine/Database/db_MYSQL.php on line 354
Duplicate entry '0' for key 'PRIMARY'

i cant go to multi hunter account too
it give this error:
Warning: mysql_fetch_assoc(): supplied argument is not a valid MySQL result resource in /home/u878815323/public_html/GameEngine/Database/db_MYSQL.php on line 830

what the problem?

**Comment by yi12345** [comment]
i don't know, but if you want you can try to change host or reinstall your server, because most peoples don't have this problem, and me too. in shortly, is not script problem.
