### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by MaxMad** [yi12345/TravianZ#82]
hello brother download your files yesterday and want to install I encounter this error
Warning: mysql_connect() [function.mysql-connect]: Access denied for user 'root'@'localhost' (using password: NO) in /home/u848446927/public_html/t3x50/install/include/database.php on line 30
 Access denied for user 'root'@'localhost' (using password: NO)

What could be the solution?

**Comment by gamerx159** [comment]
Try upload again orginal install folder :)

**Comment by yi12345** [comment]
yeah, is not script problem, is permission problem.

**Comment by MaxMad** [comment]
free hosting which would you recommend?

**Comment by yi12345** [comment]
free hosting is not good enoght, i recommened on localhost or paid host (and i haven't favorite one).

**Comment by MaxMad** [comment]
I used 000webhost.com but now let me give permissions to the database, so I can not install and hostinger.com feel the same.
That's why I'm looking for some other and can not find where to install

**Comment by Dylan96** [comment]
have you already tried http://altervista.org ?

**Comment by MaxMad** [comment]
Please help me!

Warning: mysqli_query() expects parameter 1 to be mysqli, null given in /home/ts1travi/public_html/t3/GameEngine/Database/db_MYSQLi.php on line 679

Warning: mysqli_fetch_array() expects parameter 1 to be mysqli_result, null given in /home/ts1travi/public_html/t3/GameEngine/Database/db_MYSQLi.php on line 680

Warning: mysqli_query() expects parameter 1 to be mysqli, null given in /home/ts1travi/public_html/t3/GameEngine/Database/db_MYSQLi.php on line 381
 Connect Error (0)

**Comment by MaxMad** [comment]
sorry for the lack of data, this error displayed when I create Multihunter

install/include/multihunter.php

**Comment by jotz** [comment]
I have same error
