### ISSUE TITLE
Add WW Villages and WW Buildingplan problem

### ISSUE THREAD

**Issue by jsemErOoR** [yi12345/TravianZ#84]
Warning: fopen(GameEngine/Prevention/cleardeleting.txt) [function.fopen]: failed to open stream: No such file or directory in /data/web/virtuals/12846/virtual/www/subdom/s2/GameEngine/Automation.php on line 322

Warning: fclose() expects parameter 1 to be resource, boolean given in /data/web/virtuals/12846/virtual/www/subdom/s2/GameEngine/Automation.php on line 323

Warning: fopen(GameEngine/Prevention/demolition.txt) [function.fopen]: failed to open stream: No such file or directory in /data/web/virtuals/12846/virtual/www/subdom/s2/GameEngine/Automation.php on line 3704

Warning: fclose() expects parameter 1 to be resource, boolean given in /data/web/virtuals/12846/virtual/www/subdom/s2/GameEngine/Automation.php on line 3705

Warning: fopen(GameEngine/Prevention/market.txt) [function.fopen]: failed to open stream: No such file or directory in /data/web/virtuals/12846/virtual/www/subdom/s2/GameEngine/Automation.php on line 862

Warning: fclose() expects parameter 1 to be resource, boolean given in /data/web/virtuals/12846/virtual/www/subdom/s2/GameEngine/Automation.php on line 863

Warning: fopen(GameEngine/Prevention/research.txt) [function.fopen]: failed to open stream: No such file or directory in /data/web/virtuals/12846/virtual/www/subdom/s2/GameEngine/Automation.php on line 3127

Warning: fclose() expects parameter 1 to be resource, boolean given in /data/web/virtuals/12846/virtual/www/subdom/s2/GameEngine/Automation.php on line 3128

Warning: fopen(GameEngine/Prevention/training.txt) [function.fopen]: failed to open stream: No such file or directory in /data/web/virtuals/12846/virtual/www/subdom/s2/GameEngine/Automation.php on line 3543

Warning: fclose() expects parameter 1 to be resource, boolean given in /data/web/virtuals/12846/virtual/www/subdom/s2/GameEngine/Automation.php on line 3544

Warning: fopen(GameEngine/Prevention/starvation.txt) [function.fopen]: failed to open stream: No such file or directory in /data/web/virtuals/12846/virtual/www/subdom/s2/GameEngine/Automation.php on line 3934

Warning: fclose() expects parameter 1 to be resource, boolean given in /data/web/virtuals/12846/virtual/www/subdom/s2/GameEngine/Automation.php on line 3935

Warning: fopen(GameEngine/Prevention/celebration.txt) [function.fopen]: failed to open stream: No such file or directory in /data/web/virtuals/12846/virtual/www/subdom/s2/GameEngine/Automation.php on line 3682

Warning: fclose() expects parameter 1 to be resource, boolean given in /data/web/virtuals/12846/virtual/www/subdom/s2/GameEngine/Automation.php on line 3683

Warning: fopen(GameEngine/Prevention/sendunits.txt) [function.fopen]: failed to open stream: No such file or directory in /data/web/virtuals/12846/virtual/www/subdom/s2/GameEngine/Automation.php on line 942

Warning: fclose() expects parameter 1 to be resource, boolean given in /data/web/virtuals/12846/virtual/www/subdom/s2/GameEngine/Automation.php on line 943

Warning: fopen(GameEngine/Prevention/sendreinfunits.txt) [function.fopen]: failed to open stream: No such file or directory in /data/web/virtuals/12846/virtual/www/subdom/s2/GameEngine/Automation.php on line 2941

Warning: fclose() expects parameter 1 to be resource, boolean given in /data/web/virtuals/12846/virtual/www/subdom/s2/GameEngine/Automation.php on line 2942

Warning: fopen(GameEngine/Prevention/returnunits.txt) [function.fopen]: failed to open stream: No such file or directory in /data/web/virtuals/12846/virtual/www/subdom/s2/GameEngine/Automation.php on line 3014

Warning: fclose() expects parameter 1 to be resource, boolean given in /data/web/virtuals/12846/virtual/www/subdom/s2/GameEngine/Automation.php on line 3015

Warning: fopen(GameEngine/Prevention/settlers.txt) [function.fopen]: failed to open stream: No such file or directory in /data/web/virtuals/12846/virtual/www/subdom/s2/GameEngine/Automation.php on line 3075

Warning: fclose() expects parameter 1 to be resource, boolean given in /data/web/virtuals/12846/virtual/www/subdom/s2/GameEngine/Automation.php on line 3076

Warning: mysql_num_rows() expects parameter 1 to be resource, boolean given in /data/web/virtuals/12846/virtual/www/subdom/s2/GameEngine/Database/db_MYSQL.php on line 354
Duplicate entry '0' for key 'PRIMARY'

**Comment by yi12345** [comment]
is host problem, no script problem, so i can't help, sorry.

**Comment by jsemErOoR** [comment]
Host problem? I testing 7+ hosts and is error on alls host!

**Comment by yi12345** [comment]
sorry, i saw it short time ago, but now fixed, i will upload soon.
