### ISSUE TITLE
error installing oasis

### ISSUE THREAD

**Issue by nur1labs** [yi12345/TravianZ#89]
Warning: include(../GameEngine/config.php) [function.include]: failed to open stream: No such file or directory in C:\AppServ\www\OccultTrv\GameEngine\Admin\database.php on line 23

Warning: include() [function.include]: Failed opening '../GameEngine/config.php' for inclusion (include_path='.;C:\php5\pear') in C:\AppServ\www\OccultTrv\GameEngine\Admin\database.php on line 23

Warning: include(../GameEngine/Data/buidata.php) [function.include]: failed to open stream: No such file or directory in C:\AppServ\www\OccultTrv\GameEngine\Admin\database.php on line 24

Warning: include() [function.include]: Failed opening '../GameEngine/Data/buidata.php' for inclusion (include_path='.;C:\php5\pear') in C:\AppServ\www\OccultTrv\GameEngine\Admin\database.php on line 24

Warning: Cannot modify header information - headers already sent by (output started at C:\AppServ\www\OccultTrv\GameEngine\Admin\database.php:23) in C:\AppServ\www\OccultTrv\install\include\oasis.php on line 19

**Comment by akshay9** [comment]
download latest files and reinstall.
and don`t click back button or reload button during install.

**Comment by akshay9** [comment]
if error still exists use
<? ob_start(); ?>
at the top

**Comment by nur1labs** [comment]
sir i have problem too...when it installed on PHP 5.4 have many bug....what i can do?

**Comment by akshay9** [comment]
if error still exists use
<? ob_start(); ?>
at the top

**Comment by nur1labs** [comment]
and <? ob_flush(); ?> ??? on below....

sir after i using that thing got many error wait...

login

You must have cookies enabled to be able to log in. If you share this computer with other people you should log out after each session for your own safety.

Server will start in:
NaN:NaN:NaN

what that mean?

**Comment by akshay9** [comment]
have you changed the default timezone in any of the pages like village.php

don`t use <? ob_flush(); ?>

and if your previous bug is fixed plz close this issue and start the new bug in new window
