### ISSUE TITLE
Automation.php error

### ISSUE THREAD

**Issue by Dylan96** [yi12345/TravianZ#97]
I have this error :

Warning: array_keys() [function.array-keys]: The first argument should be an array in /membri/travianxt/GameEngine/Automation.php on line 276

Warning: Invalid argument supplied for foreach() in /membri/travianxt/GameEngine/Automation.php on line 276

More error :

Warning: Cannot use a scalar value as an array in /membri/travianxt/GameEngine/Automation.php on line 1466

Warning: Cannot use a scalar value as an array in /membri/travianxt/GameEngine/Automation.php on line 1467

Warning: Cannot use a scalar value as an array in /membri/travianxt/GameEngine/Automation.php on line 1468

Warning: Cannot use a scalar value as an array in /membri/travianxt/GameEngine/Automation.php on line 1469

Warning: Cannot use a scalar value as an array in /membri/travianxt/GameEngine/Automation.php on line 1470

Look here: http://travianxt.altervista.org/login.php

**Comment by akshay9** [comment]
bro i think your problem is already fixed,
i don`t see any error

**Comment by Dylan96** [comment]
Fixed
